=== uPortal-contrib/CardWebComponents/static/i18n/jsonschema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "CardWebComponents Schema",
  "required": [
    "imgsrc",
    "title",
    "time",
    "linkMenu1",
    "linkMenu2",
    "linkMenu3",
    "List",
    "paragraphs",
    "button1",
    "button2"
  ],
  "properties": {
    "imgsrc": {
      "$id": "#/properties/imgsrc",
      "type": "string",
      "title": "The Imgsrc Schema",
      "default": "",
      "examples": [
        "https://cousquer.github.io/apereo2017/assets/artworks/apereo-uportal.jpg"
      ],
      "pattern": "^(.*)$"
    },
    "title": {
      "$id": "#/properties/title",
      "type": "string",
      "title": "The Title Schema",
      "default": "",
      "examples": ["What is uPortal?"],
      "pattern": "^(.*)$"
    },
    "time": {
      "$id": "#/properties/time",
      "type": "string",
      "title": "The Time Schema",
      "default": "",
      "examples": ["June 13, 2018"],
      "pattern": "^(.*)$"
    },
    "linkMenu1": {
      "$id": "#/properties/linkMenu1",
      "type": "object",
      "title": "The Linkmenu1 Schema",
      "required": [
        "id",
        "cssClass",
        "glyphicon",
        "iconColor",
        "label",
        "link",
        "name"
      ],
      "properties": {
        "id": {
          "$id": "#/properties/linkMenu1/properties/id",
          "type": "string",
          "title": "The Id Schema",
          "default": "",
          "examples": ["museum-menu-item-1"],
          "pattern": "^(.*)$"
        },
        "cssClass": {
          "$id": "#/properties/linkMenu1/properties/cssClass",
          "type": "string",
          "title": "The Cssclass Schema",
          "default": "",
          "examples": ["share-icon lightblue"],
          "pattern": "^(.*)$"
        },
        "glyphicon": {
          "$id": "#/properties/linkMenu1/properties/glyphicon",
          "type": "string",
          "title": "The Glyphicon url Schema",
          "default": "",
          "examples": ["brands/twitter.svg"],
          "pattern": "^(.*)$"
        },
        "iconColor": {
          "$id": "#/properties/linkMenu1/properties/iconColor",
          "type": "string",
          "title": "The Icon color css Class Schema",
          "default": "",
          "examples": ["icon-white"],
          "pattern": "^(.*)$"
        },
        "label": {
          "$id": "#/properties/linkMenu1/properties/label",
          "type": "string",
          "title": "The Label Schema",
          "default": "",
          "examples": ["Twitter: uPortal"],
          "pattern": "^(.*)$"
        },
        "link": {
          "$id": "#/properties/linkMenu1/properties/link",
          "type": "string",
          "title": "The Link url Schema",
          "default": "",
          "examples": ["https://twitter.com/uPortal"],
          "pattern": "^(.*)$"
        },
        "name": {
          "$id": "#/properties/linkMenu1/properties/name",
          "type": "string",
          "title": "The Name Schema",
          "default": "",
          "examples": ["Twitter: uPortal"],
          "pattern": "^(.*)$"
        }
      }
    },
    "linkMenu2": {
      "$id": "#/properties/linkMenu2",
      "type": "object",
      "title": "The Linkmenu2 Schema",
      "required": [
        "id",
        "cssClass",
        "glyphicon",
        "iconColor",
        "label",
        "link",
        "name"
      ],
      "properties": {
        "id": {
          "$id": "#/properties/linkMenu2/properties/id",
          "type": "string",
          "title": "The Id Schema",
          "default": "",
          "examples": ["museum-menu-item-2"],
          "pattern": "^(.*)$"
        },
        "cssClass": {
          "$id": "#/properties/linkMenu2/properties/cssClass",
          "type": "string",
          "title": "The Cssclass Schema",
          "default": "",
          "examples": ["share-icon strongblue"],
          "pattern": "^(.*)$"
        },
        "glyphicon": {
          "$id": "#/properties/linkMenu2/properties/glyphicon",
          "type": "string",
          "title": "The Glyphicon url Schema",
          "default": "",
          "examples": ["solid/envelope.svg"],
          "pattern": "^(.*)$"
        },
        "iconColor": {
          "$id": "#/properties/linkMenu2/properties/iconColor",
          "type": "string",
          "title": "The Iconcolor css Class Schema",
          "default": "",
          "examples": ["icon-white"],
          "pattern": "^(.*)$"
        },
        "label": {
          "$id": "#/properties/linkMenu2/properties/label",
          "type": "string",
          "title": "The Label Schema",
          "default": "",
          "examples": ["Contact"],
          "pattern": "^(.*)$"
        },
        "link": {
          "$id": "#/properties/linkMenu2/properties/link",
          "type": "string",
          "title": "The Link Schema",
          "default": "",
          "examples": ["mailto:uportal-user@apereo.org"],
          "pattern": "^(.*)$"
        },
        "name": {
          "$id": "#/properties/linkMenu2/properties/name",
          "type": "string",
          "title": "The Name Schema",
          "default": "",
          "examples": ["Contact"],
          "pattern": "^(.*)$"
        }
      }
    },
    "linkMenu3": {
      "$id": "#/properties/linkMenu3",
      "type": "object",
      "title": "The Linkmenu3 Schema",
      "required": [
        "id",
        "cssClass",
        "glyphicon",
        "iconColor",
        "label",
        "link",
        "name"
      ],
      "properties": {
        "id": {
          "$id": "#/properties/linkMenu3/properties/id",
          "type": "string",
          "title": "The Id Schema",
          "default": "",
          "examples": ["museum-menu-item-3"],
          "pattern": "^(.*)$"
        },
        "cssClass": {
          "$id": "#/properties/linkMenu3/properties/cssClass",
          "type": "string",
          "title": "The Cssclass Schema",
          "default": "",
          "examples": ["share-icon black"],
          "pattern": "^(.*)$"
        },
        "glyphicon": {
          "$id": "#/properties/linkMenu3/properties/glyphicon",
          "type": "string",
          "title": "The Glyphicon url Schema",
          "default": "",
          "examples": ["brands/github.svg"],
          "pattern": "^(.*)$"
        },
        "iconColor": {
          "$id": "#/properties/linkMenu3/properties/iconColor",
          "type": "string",
          "title": "The Iconcolor Schema",
          "default": "",
          "examples": ["icon-white"],
          "pattern": "^(.*)$"
        },
        "label": {
          "$id": "#/properties/linkMenu3/properties/label",
          "type": "string",
          "title": "The Label Schema",
          "default": "",
          "examples": ["Github: uPortal"],
          "pattern": "^(.*)$"
        },
        "link": {
          "$id": "#/properties/linkMenu3/properties/link",
          "type": "string",
          "title": "The Link url Schema",
          "default": "",
          "examples": ["https://github.com/jasig/uPortal"],
          "pattern": "^(.*)$"
        },
        "name": {
          "$id": "#/properties/linkMenu3/properties/name",
          "type": "string",
          "title": "The Name Schema",
          "default": "",
          "examples": ["Github: uPortal"],
          "pattern": "^(.*)$"
        }
      }
    },
    "List": {
      "$id": "#/properties/List",
      "type": "array",
      "title": "The List Tags Schema",
      "items": {
        "$id": "#/properties/List/items",
        "type": "object",
        "title": "The Items Schema",
        "required": ["tag"],
        "properties": {
          "tag": {
            "$id": "#/properties/List/items/properties/tag",
            "type": "string",
            "title": "The Tag name Schema",
            "default": "",
            "examples": ["Open source"],
            "pattern": "^(.*)$"
          }
        }
      }
    },
    "paragraphs": {
      "$id": "#/properties/paragraphs",
      "type": "array",
      "title": "The Paragraphs Schema",
      "items": {
        "$id": "#/properties/paragraphs/items",
        "type": "object",
        "title": "The Items Schema",
        "required": ["para"],
        "properties": {
          "para": {
            "$id": "#/properties/paragraphs/items/properties/para",
            "type": "string",
            "title": "The Para Schema",
            "default": "",
            "examples": [
              "<a href='http://www.apereo.org/uportal' rel='noreferrer noopener' target='_blank'>uPortal</a> is a free and open source Java-implemented web portal platform developed and maintained by participants drawn from across higher education under the coordination of <a href='http://www.apereo.org/' rel='noreferrer noopener' target='_blank'>Apereo</a>. "
            ],
            "pattern": "^(.*)$"
          }
        }
      }
    },
    "button1": {
      "$id": "#/properties/button1",
      "type": "object",
      "title": "The Button1 Schema",
      "required": [
        "id",
        "cssClass",
        "glyphicon",
        "iconColor",
        "label",
        "link",
        "name"
      ],
      "properties": {
        "id": {
          "$id": "#/properties/button1/properties/id",
          "type": "string",
          "title": "The Id Schema",
          "default": "",
          "examples": ["museum-button-1"],
          "pattern": "^(.*)$"
        },
        "cssClass": {
          "$id": "#/properties/button1/properties/cssClass",
          "type": "string",
          "title": "The Cssclass Schema",
          "default": "",
          "examples": ["btn btn-default btn-lg"],
          "pattern": "^(.*)$"
        },
        "glyphicon": {
          "$id": "#/properties/button1/properties/glyphicon",
          "type": "string",
          "title": "The Glyphicon url Schema",
          "default": "",
          "examples": ["brands/github.svg"],
          "pattern": "^(.*)$"
        },
        "iconColor": {
          "$id": "#/properties/button1/properties/iconColor",
          "type": "string",
          "title": "The Iconcolor css Class Schema",
          "default": "",
          "examples": ["icon-black"],
          "pattern": "^(.*)$"
        },
        "label": {
          "$id": "#/properties/button1/properties/label",
          "type": "string",
          "title": "The Title Attribute Schema",
          "default": "",
          "examples": ["Check the sources on Github"],
          "pattern": "^(.*)$"
        },
        "link": {
          "$id": "#/properties/button1/properties/link",
          "type": "string",
          "title": "The Link Schema",
          "default": "",
          "examples": ["https://github.com/jasig/uportal-start"],
          "pattern": "^(.*)$"
        },
        "name": {
          "$id": "#/properties/button1/properties/name",
          "type": "string",
          "title": "The Label Schema",
          "default": "",
          "examples": ["uPortal-Start"],
          "pattern": "^(.*)$"
        }
      }
    },
    "button2": {
      "$id": "#/properties/button2",
      "type": "object",
      "title": "The Button2 Schema",
      "required": [
        "id",
        "cssClass",
        "glyphicon",
        "iconColor",
        "label",
        "link",
        "name"
      ],
      "properties": {
        "id": {
          "$id": "#/properties/button2/properties/id",
          "type": "string",
          "title": "The Id Schema",
          "default": "",
          "examples": ["museum-button-2"],
          "pattern": "^(.*)$"
        },
        "cssClass": {
          "$id": "#/properties/button2/properties/cssClass",
          "type": "string",
          "title": "The Cssclass Schema",
          "default": "",
          "examples": ["btn btn-danger btn-lg"],
          "pattern": "^(.*)$"
        },
        "glyphicon": {
          "$id": "#/properties/button2/properties/glyphicon",
          "type": "string",
          "title": "The Glyphicon url Schema",
          "default": "",
          "examples": ["solid/book.svg"],
          "pattern": "^(.*)$"
        },
        "iconColor": {
          "$id": "#/properties/button2/properties/iconColor",
          "type": "string",
          "title": "The Iconcolor css Class Schema",
          "default": "",
          "examples": ["icon-white"],
          "pattern": "^(.*)$"
        },
        "label": {
          "$id": "#/properties/button2/properties/label",
          "type": "string",
          "title": "The title Attribute Schema",
          "default": "",
          "examples": ["English Documentation"],
          "pattern": "^(.*)$"
        },
        "link": {
          "$id": "#/properties/button2/properties/link",
          "type": "string",
          "title": "The Link Schema",
          "default": "",
          "examples": ["http://jasig.github.io/uPortal/"],
          "pattern": "^(.*)$"
        },
        "name": {
          "$id": "#/properties/button2/properties/name",
          "type": "string",
          "title": "The Name Schema",
          "default": "",
          "examples": ["Manual"],
          "pattern": "^(.*)$"
        }
      }
    }
  }
}

=== uPortal-contrib/CardWebComponents/i18n/en-US/messages.json
{
  "imgsrc": "https://cousquer.github.io/apereo2017/assets/artworks/apereo-uportal.jpg",
  "title": "What is uPortal?",
  "time": "June 13, 2018",
  "linkMenu1": {
    "id": "museum-menu-item-1",
    "cssClass": "share-icon lightblue",
    "glyphicon": "brands/twitter.svg",
    "iconColor": "icon-white",
    "label": "Twitter: uPortal",
    "link": "https://twitter.com/uPortal",
    "name": "Twitter: uPortal"
  },
  "linkMenu2": {
    "id": "museum-menu-item-2",
    "cssClass": "share-icon strongblue",
    "glyphicon": "solid/envelope.svg",
    "iconColor": "icon-white",
    "label": "Contact",
    "link": "mailto:uportal-user@apereo.org",
    "name": "Contact"
  },
  "linkMenu3": {
    "id": "museum-menu-item-3",
    "cssClass": "share-icon black",
    "glyphicon": "brands/github.svg",
    "iconColor": "icon-white",
    "label": "Github: uPortal",
    "link": "https://github.com/jasig/uPortal",
    "name": "Github: uPortal"
  },
  "List": [{ "tag": "Open source" }, { "tag": "Apereo" }, { "tag": "Portal" }],
  "paragraphs": [
    {
      "para": "<a href='http://www.apereo.org/uportal' rel='noreferrer noopener' target='_blank'>uPortal</a> is a free and open source Java-implemented web portal platform developed and maintained by participants drawn from across higher education under the coordination of <a href='http://www.apereo.org/' rel='noreferrer noopener' target='_blank'>Apereo</a>. uPortal can aggregate content, present self-service applications, personalize presentation and content on the basis of groups and user attributes, drive mobile device applications, and allow advanced end-user-participatory customization of the portal experience. uPortal supports the JSR-286 and JSR-168 Java portlet specification for including your custom applications within the portal."
    },
    { "para": "Welcome to uPortal." }
  ],
  "button1": {
    "id": "museum-button-1",
    "cssClass": "btn btn-default btn-lg",
    "glyphicon": "brands/github.svg",
    "iconColor": "icon-black",
    "label": "Check the sources on Github",
    "link": "https://github.com/jasig/uportal-start",
    "name": "uPortal-Start"
  },
  "button2": {
    "id": "museum-button-2",
    "cssClass": "btn btn-danger btn-lg",
    "glyphicon": "solid/book.svg",
    "iconColor": "icon-white",
    "label": "English Documentation",
    "link": "http://jasig.github.io/uPortal/",
    "name": "Manual"
  }
}
